name: test_aftershocks
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.21.5
  - shapely=1.8.0
  - pandas=1.4.3
  - mercantile=1.2.1
  - matplotlib==3.7.0
  - pip
  - sphinix==5.0.2
  - sphinx-rtd-theme
  - myst_parser
