name: test_aftershocks
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.21.5
  - shapely=1.8.0
  - pandas=1.4.3
  - mercantile=1.2.1
  - pip
  - pip:
    - copy
    - more-itertools==9.0.0
    - matplotlib==3.7.0
    - packaging==23.0
    - fonttools==4.38.0
    - kiwisolver==1.4.4
    - contourpy==1.0.7
    - Pillow==9.4.0
    - pyparsing==3.0.9
    - zipp==3.13.0
    - cycler==0.11.0
    - fonttools==4.38.0
    - matplotlib-label-lines==0.5.1
    #- matplotlib-label-lines==0.5.1
