name: test_aftershocks
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.21.5
  - shapely=1.8.0
  - matplotlib=3.7.0
  - pandas=1.4.3
  - labellines=0.5.1
  - json=2.0.9
  - mercantile=1.2.1
  - copy
  - json=2.0.9
